# Generated by Django 5.1 on 2024-08-13 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.BooleanField(default=False)),
                ('curso', models.CharField(max_length=50)),
                ('tipo_inscripcion', models.CharField(max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.alumno')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.pago')),
            ],
        ),
    ]
